/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Panel;

import DAO.DaoImple.NhanVienDAOIMPL;
import MODEl.Nhanvien;
import Xauth.phanquyen;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien() {
        initComponents();
        String[] columnNames = {"Mã NV", "Tên", "Giới tính", "Ngày sinh", "SĐT", "Email", "Chức vụ", "Mật khẩu", "Trạng thái"};
DefaultTableModel model = new DefaultTableModel(columnNames, 0);
tbl.setModel(model);

           phanQuyenNhanVienUI();
          

    }
private void setForm(Nhanvien nv) {
    txtMa.setText(nv.getMaNV());
    txtTen.setText(nv.getHoTen());
    sdt.setText(nv.getSdt());
    date.setDate(nv.getNgaySinh());
    txtemai.setText(nv.getEmail());
    cbb.setSelectedItem(nv.getChucVu());
    txtpass.setText(nv.getMatKhau());
    if ("Nam".equalsIgnoreCase(nv.getGioiTinh())) {
        jRadioButton1.setSelected(true);
    } else {
        jRadioButton2.setSelected(true);
    }
    jCheckBox1.setSelected(nv.isTrangThai());
}

 private Nhanvien getForm() {
    Nhanvien nv = new Nhanvien();
    nv.setMaNV(txtMa.getText());
    nv.setHoTen(txtTen.getText());
    nv.setSdt(sdt.getText());
    nv.setNgaySinh(new java.sql.Date(date.getDate().getTime()));
    nv.setEmail(txtemai.getText());
    nv.setChucVu(cbb.getSelectedItem().toString());
    nv.setMatKhau(txtpass.getText());
    nv.setGioiTinh(jRadioButton1.isSelected() ? "Nam" : "Nữ");
    nv.setTrangThai(jCheckBox1.isSelected());
    return nv;
}



   private void phanQuyenNhanVienUI() {
    if (!phanquyen.check()) { 
        btnthem.setEnabled(false);
        btnxoa.setEnabled(false);

        txtMa.setEditable(false); 
        JOptionPane.showMessageDialog(this, "Bạn chỉ được sửa thông tin của chính mình.");

        loadThongTinCaNhan(); 
    } else {
        loadTatCaNhanVien(); 
    }
}
private void loadThongTinCaNhan() {
    DefaultTableModel model = (DefaultTableModel) tbl.getModel();
    model.setRowCount(0);

    Nhanvien nv = phanquyen.user;
    model.addRow(new Object[]{
        nv.getMaNV(),
        nv.getHoTen(),
        nv.getGioiTinh(),
        nv.getNgaySinh(),
        nv.getSdt(),
        nv.getEmail(),
        nv.getChucVu(),
        nv.isTrangThai() ? "Đang làm" : "Nghỉ"
    });
}
private void loadTatCaNhanVien() {
    DefaultTableModel model = (DefaultTableModel) tbl.getModel();
    model.setRowCount(0);
    NhanVienDAOIMPL dao = new NhanVienDAOIMPL();
    List<Nhanvien> list = dao.getAll();
    for (Nhanvien nv : list) {
        model.addRow(new Object[]{
            nv.getMaNV(),
            nv.getHoTen(),
            nv.getGioiTinh(),
            nv.getNgaySinh(),
            nv.getSdt(),
            nv.getEmail(),
            nv.getChucVu(),
          //  nv.getMatKhau(), 
            nv.isTrangThai() ? "Đang làm" : "Nghỉ"
        });
    }
}
private void clearForm() {
    txtMa.setText("");
    txtTen.setText("");
    sdt.setText("");
    txtemai.setText("");
    txtpass.setText("");
    cbb.setSelectedIndex(0);
    date.setDate(null);
    jRadioButton1.setSelected(true); 
    jCheckBox1.setSelected(true); 
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpass = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnthem = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        cbb = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        btnsua = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sdt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txttenlog = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        txtemai = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1620, 1080));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 180, 280, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Tên nhân viên");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Ngày Sinh");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Chức vụ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Tên Đăng Nhập");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, -1, -1));

        btnthem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnthem.setForeground(new java.awt.Color(0, 102, 102));
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });
        add(btnthem, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Mật Khẩu ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 160, -1, -1));

        btnxoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnxoa.setForeground(new java.awt.Color(0, 102, 102));
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });
        add(btnxoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, -1, -1));

        date.setDateFormatString("yyyy-MM-dd");
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 280, -1));

        cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "nhân viên", "quản lí" }));
        add(cbb, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 280, -1));

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên", "Sdt", "Ngày Sinh", "ChucVu", "TênLogin", "Pass"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 418, 1518, 520));

        btnsua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsua.setForeground(new java.awt.Color(0, 102, 102));
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });
        add(btnsua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1071, 383, -1, -1));

        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("Load");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Quản lí nhân viên");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, -1, -1));
        add(sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 120, 280, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Mã nhân viên ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("SĐT");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 90, -1, -1));
        add(txtMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 280, -1));
        add(txttenlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 180, 280, -1));

        txtTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenActionPerformed(evt);
            }
        });
        add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 280, -1));

        jRadioButton1.setText("Nam");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jRadioButton2.setText("Nữ");
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        jCheckBox1.setText("Làm/Nghĩ");
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));
        add(txtemai, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 280, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
  Nhanvien nv = getForm();
    NhanVienDAOIMPL dao = new NhanVienDAOIMPL();

    if (dao.findById(nv.getMaNV()) != null) {
        JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại!");
        return;
    }

    if (dao.insert(nv)) {
        JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
        loadTatCaNhanVien();
        clearForm();
    } else {
        JOptionPane.showMessageDialog(this, "Thêm thất bại!");
    }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
  if (!phanquyen.check()) {
        JOptionPane.showMessageDialog(this, "Bạn không có quyền xóa nhân viên.");
        return;
    }

    int row = tbl.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần xóa.");
        return;
    }

    String ma = tbl.getValueAt(row, 0).toString();
    int confirm = JOptionPane.showConfirmDialog(this, "Xác nhận xóa nhân viên: " + ma + "?");

    if (confirm == JOptionPane.YES_OPTION) {
        NhanVienDAOIMPL dao = new NhanVienDAOIMPL();
        if (dao.delete(ma)) {
            JOptionPane.showMessageDialog(this, "Xoá thành công!");
            loadTatCaNhanVien();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Xoá thất bại!");
        }
    }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        // TODO add your handling code here:
  int row = tbl.getSelectedRow();
    if (row >= 0) {
        String ma = tbl.getValueAt(row, 0).toString();
        NhanVienDAOIMPL dao = new NhanVienDAOIMPL();
        Nhanvien nv = dao.findById(ma);
        if (nv != null) {
            setForm(nv);
        }
    }

    }//GEN-LAST:event_tblMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
      int row = tbl.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn dòng cần sửa.");
        return;
    }

    String maNV = tbl.getValueAt(row, 0).toString();

    if (!phanquyen.check() && !maNV.equals(phanquyen.user.getMaNV())) {
        JOptionPane.showMessageDialog(this, "Bạn chỉ được sửa thông tin của chính mình.");
        return;
    }

    NhanVienDAOIMPL dao = new NhanVienDAOIMPL();
    Nhanvien nv = getForm();

    if (dao.update(nv)) {
        JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        loadTatCaNhanVien();
        clearForm();
    } else {
        JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
    }

    }//GEN-LAST:event_btnsuaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbb;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sdt;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtemai;
    private javax.swing.JTextField txtpass;
    private javax.swing.JTextField txttenlog;
    // End of variables declaration//GEN-END:variables
}
