/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Panel;

import DAO.DaoImple.chamcongdao;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.google.zxing.*;
import com.google.zxing.common.HybridBinarizer;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.sql.Timestamp;
import java.time.LocalDateTime;

/**
 *
 * @author Admin
 */
public class quetmaqr extends javax.swing.JPanel implements Runnable {

    private Webcam webcam;
    private Thread thread;
    private chamcongdao dao = new chamcongdao();

    /**
     * Creates new form quetmaqr
     */
    public quetmaqr() {
        initComponents();
        setLayout(new BorderLayout());
        webcam = Webcam.getDefault();
        if (webcam == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy webcam!");
            return;
        }
        WebcamPanel panel = new WebcamPanel(webcam);
        add(panel, BorderLayout.CENTER);
        thread = new Thread(this);
        thread.start();
    }

    @Override
    public void run() {
        while (true) {
            try {
                BufferedImage image = webcam.getImage();
                if (image == null) {
                    continue;
                }

                LuminanceSource source = new BufferedImageLuminanceSource(image);
                BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

                Result result = new MultiFormatReader().decode(bitmap);
                if (result != null) {
                   String rawText = result.getText();
                    String maNV = rawText;

                    if (rawText.contains("=")) {
                       String[] parts = rawText.split("=");
                  if (parts.length == 2) {
                    maNV = parts[1]; 
                }
                }

                    Timestamp now = Timestamp.valueOf(LocalDateTime.now());

                    if (daMoCa(maNV)) {
                        if (dao.updateGioRa(maNV, now)) {
                            JOptionPane.showMessageDialog(this, "✅ Kết ca: " + maNV);
                        } else {
                            JOptionPane.showMessageDialog(this, "❌ Không thể kết ca.");
                        }
                    } else {
                        if (dao.insertChamCong(maNV, now)) {
                            JOptionPane.showMessageDialog(this, "✅ Bắt đầu ca: " + maNV);
                        } else {
                            JOptionPane.showMessageDialog(this, "❌ Không thể chấm công.");
                        }
                    }

                    Thread.sleep(3000); 
                }
            } catch (NotFoundException e) {
               
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private boolean daMoCa(String maNV) {
      
        return dao.daMoCa(maNV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
