/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Panel;
import DAO.DaoImple.HoaDonDAO;
import javax.swing.*;
import java.awt.*;
import java.util.Map;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import java.util.Calendar;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author Admin
 */
public class thongke extends javax.swing.JPanel {

    /**
     * Creates new form thongke
     */
    HoaDonDAO dao= new HoaDonDAO();
    public thongke() {
        initComponents();
            initNam();
    }
   private void initNam() {
    int currentYear = Calendar.getInstance().get(Calendar.YEAR);
    for (int i = 2020; i <= currentYear; i++) {
        cbbNam.addItem(String.valueOf(i)); 
    }
}



    private void hienThiBieuDo(int nam) {
        Map<Integer, Double> map = dao.getDoanhThuTheoThang(nam);

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        for (int thang = 1; thang <= 12; thang++) {
            double tien = map.getOrDefault(thang, 0.0);
            dataset.addValue(tien, "Doanh Thu", "Tháng " + thang);
        }

        JFreeChart chart = ChartFactory.createBarChart(
                "Thống kê doanh thu theo tháng - Năm " + nam,
                "Tháng", "Doanh thu (VNĐ)",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(780, 500));

        pnlBieuDo.removeAll();
        pnlBieuDo.setLayout(new BorderLayout());
        pnlBieuDo.add(chartPanel, BorderLayout.CENTER);
        pnlBieuDo.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbNam = new javax.swing.JComboBox<>();
        btnthongke = new javax.swing.JButton();
        pnlBieuDo = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1620, 1080));

        btnthongke.setText("jButton1");
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBieuDoLayout = new javax.swing.GroupLayout(pnlBieuDo);
        pnlBieuDo.setLayout(pnlBieuDoLayout);
        pnlBieuDoLayout.setHorizontalGroup(
            pnlBieuDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlBieuDoLayout.setVerticalGroup(
            pnlBieuDoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnthongke))
                .addContainerGap(1340, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBieuDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(cbbNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnthongke)
                .addGap(37, 37, 37)
                .addComponent(pnlBieuDo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        // TODO add your handling code here:
         int nam = Integer.parseInt(cbbNam.getSelectedItem().toString());
        hienThiBieuDo(nam);
    }//GEN-LAST:event_btnthongkeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthongke;
    private javax.swing.JComboBox<String> cbbNam;
    private javax.swing.JPanel pnlBieuDo;
    // End of variables declaration//GEN-END:variables
}
